from __future__ import annotations

from pathlib import Path
from typing import Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.db.models import Video
from src.services.storage import ensure_media_dirs, get_video_dir


# PUBLIC_INTERFACE
async def seed_if_empty(session: AsyncSession, sample_video_path: Optional[Path] = None) -> bool:
    """Seed the database with a sample video if the videos table is empty.

    This utility is intended for development environments only.

    Args:
        session: Active AsyncSession.
        sample_video_path: Optional path to a sample video file to register. If not provided,
            an empty placeholder file will be created in the configured media/videos directory.

    Returns:
        True if seeding was performed, False if not needed.
    """
    res = await session.execute(select(Video.id).limit(1))
    first = res.scalar()
    if first:
        return False

    # Ensure media directories exist
    ensure_media_dirs()
    target_dir = get_video_dir()

    # If no sample provided, create a small placeholder file to register
    if sample_video_path is None:
        target_file = target_dir / "sample.mp4"
        if not target_file.exists():
            # Create a small empty file placeholder; in a real setup place a valid small mp4.
            target_file.touch()
    else:
        target_file = target_dir / sample_video_path.name
        if not target_file.exists():
            # Copy-like: read and write chunks to avoid dependency on shutil for big files
            with sample_video_path.open("rb") as src, target_file.open("wb") as dst:
                while True:
                    chunk = src.read(1024 * 1024)
                    if not chunk:
                        break
                    dst.write(chunk)

    v = Video(
        title="Sample Video",
        description="Autogenerated sample on first run",
        file_path=str(target_file),
    )
    session.add(v)
    await session.flush()
    return True
